name: Build and Release

on:
  push:
    branches:
      - main

# Compilar a Windows
jobs:
  build-windows:
    env:
      name: XLauncher
      version: 1.0.3
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python 3.11.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Build with pyinstaller
      run: |
        pyinstaller main.py --noconfirm --onedir --console --icon icon_windows.ico --name "XLauncher"
    - name: Compress folder
      shell: powershell
      run: |
        Compress-Archive -Path dist/XLauncher -DestinationPath XLauncher-Windows.zip

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.name }}-Windows
        path: ./dist

# Compilar a Ubuntu

  build-ubuntu:
    runs-on: ubuntu-latest
    env:
      name: XLauncher
      version: 1.0.3

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python 3.11.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Build with pyinstaller
      run: |
        pyinstaller main.py --onefile --icon icon_windows.ico --name "XLauncher"
    - name: Compress folder
      run: |
        zip XLauncher-Ubuntu.zip dist/XLauncher

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.name }}-ubuntu
        path: ./dist
